name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Install mpi
      run: sudo apt-get install -y mpich
      
    - name: checkout repository
      uses: actions/checkout@v4
      with:
        ref: main
        submodules: recursive
        
    - name: make
      run: mkdir -p build && cd build && cmake .. && cmake --build .

    - name: make
      run: cd build && ./test_multiplication 

    
