name: TEST CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    name : Build Application 
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: install 'expect' 
      run: |
        sudo apt install expect

    - name: Group files to Send
      run : mkdir to_send && mv job.sh to_send/  && mv container.sif to_send/

    - name: Send file to Galileo
      env:
        SSH_GALILEO: ${{ secrets.SSHGALILEO }}
      run: |
        # sudo chmod a+x .github/workflows/uploader.sh
        # .github/workflows/uploader.sh $SSH_GALILEO to_send

    - name: SSH to remote server
      env:
        SSHPASS: ${{ secrets.SSHGALILEO }}
      run: |
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan -t rsa login.g100.cineca.it >> ~/.ssh/known_hosts
        sshpass -e scp -r to_send a08trb58@login.g100.cineca.it:~/
        ssh-keygen -f "/home/runner/.ssh/known_hosts" -R "login.g100.cineca.it"
        sshpass -e ssh -o StrictHostKeyChecking=no -tt a08trb58@login.g100.cineca.it << 'EOF'
        ls
        rm -rf santarsiero_ferrario_sweng_part2
        git clone https://github.com/dome01polimi/santarsiero_ferrario_sweng_part2
        mv to_send/container.sif santarsiero_ferrario_sweng_part2/
        chmod +x to_send/job.sh 
        sbatch to_send/job.sh
        squeue --me
        exit      
        EOF