name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: checkout repository
      uses: actions/checkout@v4
      with:
        ref: main
        submodules: recursive
        
    - name: mkdir
      run: mkdir -p build
      
    - name: make
      run: cd build && cmake .. && cmake --build .

    
