name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: install mpi
      run: sudo apt-get update && sudo apt-get install -y mpich

    - name: checkout repository
      uses: actions/checkout@v4
      with:
        ref: main
        submodules: recursive

    - name: install dependencies for Singularity 
      run: |
        sudo apt-get install -y \
           build-essential \
           libseccomp-dev \
           pkg-config \
           squashfs-tools \
           cryptsetup \
           curl wget git
        
    - name: install Go
      run: |
        export GOVERSION=1.17.3 OS=linux ARCH=amd64
        wget -O /tmp/go${GOVERSION}.${OS}-${ARCH}.tar.gz \
          https://dl.google.com/go/go${GOVERSION}.${OS}-${ARCH}.tar.gz
        sudo tar -C /usr/local -xzf /tmp/go${GOVERSION}.${OS}-${ARCH}.tar.gz

    - name : setupe Env for GO
      run: echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc && source ~/.bashrc
  
    - name : install Singularity
      uses: eWaterCycle/setup-singularity@v7
      with:
          singularity-version: 3.8.3
          run : singularity --version
    
    - name: make    
      run: mkdir -p build && cd build && cmake .. && cmake --build .

    - name: test
      run: cd build && ./test_multiplication 

    
