name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Application 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install Expect
      run: sudo apt install expect
      
      
    - name: Send file to Galileo
      env:
        SSH_GALILEO: ${{ secrets.SSHGALILEO }}
      run: |
        echo $SSH_GALILEO
        sudo chmod a+x .github/workflows/uploader.sh
        .github/workflows/uploader.sh $SSH_GALILEO Singularity.def job.sh
